
ex1_a: 1a.c
	gcc -o 1a 1a.c 	
	./1a


ex1_b: linked_list.c linked_list.h list_test.c
	gcc -o 1b linked_list.c linked_list.h list_test.c
	./1b

ex1_c: 3a.c
	gcc -g -Wall -pthread 3a.c -lpthread -lrt -o 3a
	./3a
